/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package opensl;

public class opensl {
  public static void start_process() {
    openslJNI.start_process();
  }

  public static void stop_process() {
    openslJNI.stop_process();
  }

}
